### ISSUE TITLE
Adaptive Control System

### ISSUE THREAD

**Issue by Supereaglecoder** [Crzyrndm/Pilot-Assistant#11]
Hi Cryzrndm,

          First off, I want to thank you for creating this add-on.  The accuracy of the assistant  is unbelievable for me in comparison to mechjeb and the stock SAS.

           Secondly, this isn't an issue more like a suggestion, I wanted to message you directly but there is no mechanism for direct messaging.  Have you ever considered implementing an adaptive control system?  If so, I would like to be involved in that feature.

Cheers,

Supereaglecoder

**Comment by Crzyrndm** [comment]
Adaptive as in retunes itself to suit current speed/altitude/density?

I'm dealing with that through a separate mod (released today) found here:http://forum.kerbalspaceprogram.com/threads/116196-WIP-Dynamic-Control-Surface-Deflection-v0-1
