### ISSUE TITLE
Binds to tab key.

### ISSUE THREAD

**Issue by phmayo** [Crzyrndm/Pilot-Assistant#12]
Which means that switching focus becomes difficult without re-binding KSP default keybindings.

OS: Linux x64

**Comment by Crzyrndm** [comment]
I'm not sure I fully understand.
Yes, Pilot Assistant monitors the tab key for it's pause behaviour. What Linux shortcut is this conflicting with and why does changing KSP bindings make a difference?

**Comment by phmayo** [comment]
It messes up the KSP default binding for "switch focus to other
vessel/object" in map view, not one of my Linux keybinds (the WM specific
ones need a compose key).

This may just be an issue with Linux (we get RShift as modifier, yay), so
it's worth mentioning if that can cause problems.

**Comment by Crzyrndm** [comment]
oh, that's an easy fix then. Thanks for bringing it to my attention
