### ISSUE TITLE
Pilot Assist working with other mods?

### ISSUE THREAD

**Issue by DeputyLOL** [Crzyrndm/Pilot-Assistant#13]
Hi, not sure if this is the place for requests but I couldn't get on the forums for some reason. 
Sorry if it isn't.

First off. Pilot Assistant = Amazing!

Have you considered making PA compatible with other mods? There are other mods out there that your mod could work with, there would be unlimited potential. 

RPM has updated to allow it to both get and set numeric data from a plugin to a persistent variable and from the persistent variable to a plugin. This means you could control PA from IVA without needing to go through menus. I currently have this set up for MJ, I can hold a specific heading and altitude without needing to go through any menus, unfortunately its MJ so it immediately spazzes out and rips my plane apart. If PA exposes its variable to RPM, it would be possible to build a very advanced autopilot. 

NAV Utilities gives you directions to a runway and helps you line up, it also lets you set glide slope and runway. MJs autoland system either works badly or crashes the plane, even though you can set a glide slope, MJ will just nose dive to about 100m and then level off, only descending when it reaches the glide slope. Half the time MJ cant or wont level at 100 and just crashes. If PA had an autoland or approach function, it would be a great addition. PA has much more precision than MJ making less likely to crash.

Lastly, not really a mod but a feature. A Flight Director (FD). Basically, PA shows where it would be steering the plane but isn't in control. This leaves the pilot to fly and PA shows them where to go.

Once again, thank you for the impressive mod. I hope you consider my request and please let me know what you think. If you don't want to change it then that's fine, I understand. 
Thanks again.

**Comment by Crzyrndm** [comment]
There has been some discussion about adding RPM support in the derivative ["Kramax Autopilot"](http://forum.kerbalspaceprogram.com/threads/135840-1-0-4-Kramax-Autopilot-Course-guidance-and-auto-land-for-spaceplanes-%28v0-2%29). I haven't yet had a chance to look at what RPM requires for input.

See Kramax for autoland functionality. Kramer did a great job on that one and it's not something I wanted to have in PA.

That can't be done. Pilot assistant doesn't explicitly solve the question of what angle it should be at on each axis until the vessel reaches a stable situation at the desired state.

**Comment by DeputyLOL** [comment]
ok, thank you for the reply. I wasnt aware of kramax autopilot until after I posted this. 
MOARdv told me about it in a discussion about implementing PA into RPM.
