### ISSUE TITLE
PA "set value" usability request

### ISSUE THREAD

**Issue by MOARdV** [Crzyrndm/Pilot-Assistant#14]
One thing I've noticed with PA is that I can't set a target value (say, altitude), and then press the button to hold altitude.  In this instance, when I activate the control, the current altitude is selected, and then I have to re-enter the hold altitude.  This can be dicey if I have just cleared the runway.  Is it possible to read the current value in the input field, and use it if it makes sense?  Or, have a button / checkbox that tells PA "use the value in the input field, do not load the current setting"?

**Comment by Crzyrndm** [comment]
It activates with the current value if you click the module button (eg. vertical control). If you click the Set target button it will activate using the value in the target field.

Or am I misunderstanding something?

**Comment by MOARdV** [comment]
My apology - I'm still getting the hang of spaceplanes and PA.  Here's the issue I am having, now that I've gone back and tried it again to refresh my memory on what's going on: it's when switching modes (say, from "hold altitude" to "hold pitch").  In this instance, I can't type in a desired pitch, and then press "hold pitch".  As soon as I press "hold pitch", PA reads the current pitch and sets it as the starting pitch.  That's not too big of a deal, but if I'm in "hold pitch", and then I want to set altitude, the pilot will choose the current altitude as the set point, and then I have to type in the new altitude and set it before it takes effect; meanwhile, the craft is bouncing because it's trying to dive back down to the altitude I was at when I changed modes, even though I want to keep climbing.

I don't have a good suggestion for how to fix it - it'd require multiple input fields (one per mode).  Or maybe I'm just overlooking the right way to change modes?

**Comment by Crzyrndm** [comment]
Nope, that last one is a real pain. I normally avoid it either by switching to altitude control only level flight or quickly hitting (Alt + S) to continue climbing. I've never really got around to doing anything about it because the mode is normally used for long distance cruising so you have issues only very infrequently
