### ISSUE TITLE
Vessel launch w/ command seat + Take Command mod disables Pilot Assistant

### ISSUE THREAD

**Issue by ferram4** [Crzyrndm/Pilot-Assistant#16]
If a vehicle has only a command seat attached and is launched with the Take Command mod (so Kerbal spawns inside a "cockpit" in the command seat and then is auto-transfered to be in the seat itself) Pilot Assistant loses track of the vessel and cannot control it.  This *does not* affect vehicles that only have control via a Kerbal in a command seat that are loaded with the Kerbal already sitting in the seat.

Reproduction steps:
1. Install Take Command + Pilot Assistant 1.12.1 (no other mods necessary)
2. Create vehicle with command seat (no other parts necessary)
3. Use crew section of editor to ensure that Kerbal is placed in command seat
4. Launch.
5. Vehicle will have active Pilot Assistant until Kerbal is shifted by Take Command into command seat.  After that, vehicle requires save -> reload to have active Pilot Assistant

Note: this *was not* an issue under Pilot Assistant 1.11.7.

**Comment by Crzyrndm** [comment]
Fixed in latest commit, new release should be later today.
