### ISSUE TITLE
MM can no longer reload database.

### ISSUE THREAD

**Issue by DeputyLOL** [Crzyrndm/Pilot-Assistant#23]
I'm not entirely sure if this is Pilot Assistants fault but I have never had this problem until I installed it into KSP 1.1.
When pressing 'Quick Reload database', MM will start reloading the database but get stuck around 77%, at which point the log is full of:
[LOG 10:12:03.347] [ModuleManager] Ran in 5.806s
[LOG 10:12:03.399] [ModuleManager] Ran in 5.806s
[LOG 10:12:03.453] [ModuleManager] Ran in 5.806s
[LOG 10:12:03.500] [ModuleManager] Ran in 5.806s
[LOG 10:12:03.554] [ModuleManager] Ran in 5.806s
[LOG 10:12:03.605] [ModuleManager] Ran in 5.806s
[LOG 10:12:03.658] [ModuleManager] Ran in 5.806s
[LOG 10:12:03.710] [ModuleManager] Ran in 5.806s
[LOG 10:12:03.759] [ModuleManager] Ran in 5.806s
[LOG 10:12:03.807] [ModuleManager] Ran in 5.806s
[LOG 10:12:03.851] [ModuleManager] Ran in 5.806s
[LOG 10:12:03.899] [ModuleManager] Ran in 5.806s

It never finishes reloading database :(

Other than that, it seems to work ok.

**Comment by Crzyrndm** [comment]
........................................................................................Huh?

I will check it out (tomorrow at this point), but I'm currently clueless as to how PA manages to interfere with that...

**Comment by DeputyLOL** [comment]
btw are you aware that you only released the source code version of pilot assistant on GitHub?
Do you think that might the issue?

**Comment by Crzyrndm** [comment]
Derp, that's fixed...

**Comment by DeputyLOL** [comment]
I noticed that all the controls are a lot more jittery, is that normal?

**Comment by Crzyrndm** [comment]
Missing dynamic deflection again?

**Comment by DeputyLOL** [comment]
.... maybe...
But it seems to be a lot more jittery than the pervious build and I didn't have dynamic deflection.
It also affects the throttles.

**Comment by DeputyLOL** [comment]
Also is dynamic deflection 1.1 compatible? I didn't check and the forum says 1.0.5

**Comment by Crzyrndm** [comment]
It is, KSP versioning in that thread is still half and half

**Comment by DeputyLOL** [comment]
Apologies, this is not PAs fault, this is FAR.
I apparently didn't try reloading the database until after I installed your mod.
