### ISSUE TITLE
Hold Heading through 0/360* gets confused.

### ISSUE THREAD

**Issue by DeputyLOL** [Crzyrndm/Pilot-Assistant#24]
I think there was an issue like this before, if you are flying heading 10* and set PA to fly 350* the plane will turn the right and attempt to do a 340* turn to the target heading.

Only difference now is that the plane will start the wrong turn and then change its mind after about 10 seconds and slam the controls in the opposite direction to turn the right way.

I've also noticed that the 'Alt Hold' autopilot will first react by diving/climbing the plane in the opposite direction to what the plane was already doing. Meaning that if the plane is climbing and you set a higher altitude, PA will immediately put the plane into a dive (disregarding any limits you set) and then very slowly levels out and starts to climb. For obvious reasons, it means I cant use it during take off.

**Comment by Crzyrndm** [comment]
Noted, will fix shortly
