### ISSUE TITLE
Hold heading to target.

### ISSUE THREAD

**Issue by dak180** [Crzyrndm/Pilot-Assistant#8]
Any chance of getting the ability to hold a heading to a target taking into account the [shortest great circle distance](http://www.movable-type.co.uk/scripts/latlong.html)?

**Comment by Crzyrndm** [comment]
If you can suggest a reasonable way of choosing that final target, maybe

**Comment by dak180** [comment]
If you are speaking of a way for the user to choose the target, then I would say just tie into the ksp target system and leave it as an exercise for the user.

I can think of several ways that someone might use other tools to select a target, (flags, other vessels) personally I tend to use mechjeb's landing guidance to pick on a map or enter coordinates directly.

My biggest issue is trying to figure out the correct heading (especially since it is not constant) on really long distant flights, such as ones nearly to the other side of the world.

**Comment by Crzyrndm** [comment]
Hmm, using flags and other vessels as targets might be manageable. I'll think about it.

**Comment by Crzyrndm** [comment]
After some further consideration, I will not be implementing any targeting mechanism. It doesn't fit with the level of control I want to have with this mod.

However, I think a heading control scheme which locks to an "orbit" (or rather the plane of an orbit) is something that would fit and will be the pursued manner of feature development. This may or may not replace the current "wing leveller" function

**Comment by Crzyrndm** [comment]
Implemented a great circle style control system in the Assistant heading control

Feedback appreciated
https://github.com/Crzyrndm/Pilot-Assistant/blob/master/GameData/Pilot%20Assistant/PilotAssistant.dll?raw=true
